language: smalltalk
sudo: false

os:
  - osx

matrix:
  include:
  - smalltalk: Pharo-6.1
  - smalltalk: Pharo64-6.1


before_install:
  - |
       # Otherwise build on OSX stucks at unknown fingerprint question
       echo -e "Host *\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

       declare -r SSH_FILE="$(mktemp -u $HOME/.ssh/$GITHUB_SSH_FILE)"
       # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
       openssl aes-256-cbc \
         -K $encrypted_dc3d6cd55a6d_key \
         -iv $encrypted_dc3d6cd55a6d_iv \
         -in ".travis/github_deploy_key.enc" \
         -out "$SSH_FILE" -d

       # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

       # Enable SSH authentication

       chmod 600 "$SSH_FILE" \
         && printf "%s\n" \
              "Host github.com" \
              "  IdentityFile $SSH_FILE" \
              "  LogLevel ERROR" >> ~/.ssh/config
       cp $SSH_FILE $HOME/.ssh/id_rsa
       ssh-add $HOME/.ssh/id_rsa
       ssh-add $SSH_FILE
