language: smalltalk
sudo: false

os:
  - linux

smalltalk:
  - Pharo64-7.0

smalltalk_config:
  - .smalltalk.ston
  - .withPharoTests.ston

matrix:
  allow_failures:
    - smalltalk_config: .withPharoTests.ston
    - smalltalk: Pharo32-8.0
      smalltalk_config: .smalltalk.ston
    - smalltalk: Pharo64-8.0
      smalltalk_config: .smalltalk.ston
  include:
    - smalltalk: Pharo32-8.0
      smalltalk_config: .smalltalk.ston
    - smalltalk: Pharo64-8.0
      smalltalk_config: .smalltalk.ston
