language: smalltalk
sudo: false

os:
  - linux

smalltalk:
  - Pharo64-7.0

matrix:
  includes:
    - smalltalk: Pharo64-7.0
    - smalltalk: Pharo64-7.0
      env: BUILD_NAME=PharoWithAllTests64-7.0
      smalltalk_config: .withPharoTests.ston
  allow_failures:
    - smalltalk_config: .withPharoTests.ston
